# Generated by Django 5.0.2 on 2024-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_portal", "0002_course_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="name",
            field=models.CharField(default="Some random stuff", max_length=100),
            preserve_default=False,
        ),
    ]
